org: mixermachine
app: extreme-motivation-backend
service: extreme-motivation-backend

frameworkVersion: '2'

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: extremeMotivation-${self:custom.stage}
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: eu-central-1
  memorySize: 512
  stage: dev
  tracing:
    lambda: false
  environment:
    tableName: ${self:custom.tableName}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}
    region: ${self:custom.region}
    pieceRotationIntervalSeconds: 86400
    pieceRotationPointInTimeSecondsFromMidnight: 0
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            arn:aws:dynamodb:eu-central-1:*:*

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
